# Generated by Django 4.2.1 on 2023-05-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='About name1')),
                ('name2', models.CharField(max_length=100, verbose_name='About name2')),
                ('about', models.TextField(max_length=500, verbose_name='About Us')),
                ('img', models.ImageField(upload_to='Photo', verbose_name='About Image')),
            ],
        ),
    ]
