# Generated by Django 4.2.1 on 2023-05-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Photo', verbose_name='Project Image')),
                ('name', models.CharField(max_length=50, verbose_name='About name1')),
            ],
        ),
    ]
