# Generated by Django 4.2.1 on 2023-05-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.TextField(max_length=500, verbose_name='Contact About1')),
                ('about2', models.TextField(max_length=500, verbose_name='Contact About2')),
                ('adress1', models.CharField(max_length=50, verbose_name='Adress1')),
                ('adress2', models.CharField(max_length=50, verbose_name='Adress2')),
            ],
        ),
    ]
