# Generated by Django 4.2.1 on 2023-05-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='foot',
            field=models.CharField(default=2, max_length=50, verbose_name='Footer'),
            preserve_default=False,
        ),
    ]
